version: '3.8'

services:
  smsc-simulator-1:
    image: smsc-simulator:latest
    container_name: smsc-simulator-1
    ports:
      - "2775:2775"

  smsc-simulator-2:
    image: smsc-simulator:latest
    container_name: smsc-simulator-2
    ports:
      - "2776:2775"

  smsc-simulator-3:
    image: smsc-simulator:latest
    container_name: smsc-simulator-3
    ports:
      - "2777:2775"
